### ISSUE TITLE
Github workflow commands (::error, ::warning, etc) from a task not picked up

### ISSUE THREAD

**Issue by ericmatthys** [vercel/turbo#1363]
### What version of Turborepo are you using?

1.2.16

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Github Actions may rely on annotations from reporters for associating errors with a particular file. This is used by the Jest `github-actions` reporter. I'm having trouble getting the reporter to work in a monorepo with Turborepo, I think because the message is printed with the package + task prefix.

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message

The output from Turborepo:

```
core:test: ::error file=/home/runner/work/website/website/packages/core/utils/object/pick.spec.ts,line=9,title=pick › should ignore undefined properties::expect(received).toEqual(expected) // deep equality%0A%0A- Expected  - 1%0A+ Received  + 2%0A%0A  Object {%0A-   "a": 2,%0A+   "a": 1,%0A+   "b": undefined,%0A  }%0A%0A    at Object.toEqual (utils/object/pick.spec.ts:9:52)%0A    at TestScheduler.scheduleTests (../../node_modules/.pnpm/@jest+core@28.1.1/node_modules/@jest/core/build/TestScheduler.js:317:13)%0A    at runJest (../../node_modules/.pnpm/@jest+core@28.1.1/node_modules/@jest/core/build/runJest.js:407:19)%0A    at _run10000 (../../node_modules/.pnpm/@jest+core@28.1.1/node_modules/@jest/core/build/cli/index.js:339:7)%0A    at runCLI (../../node_modules/.pnpm/@jest+core@28.1.1/node_modules/@jest/core/build/cli/index.js:190:3)
```

### Expected Behavior

I'd expect the Jest `github-actions` reporter's annotations to be picked up by Github automatically. Perhaps this style of annotation should avoid the prefix and be printed directly, if that is actually the issue here.

### To Reproduce

Using Jest 28.1.1, add `reporters: ['default', 'github-actions']` to the Jest config file to enable the reporter. Add a failing test and trigger a workflow that runs the Jest tests within a Turborepo task.

_package.json_
```
"test": "cross-env FORCE_COLOR=1 turbo run test"
```

_packages/core/package.json_
```
"test": "cross-env TZ=UTC jest"
```

_.github/workflows/test.yml_
```yaml
name: Run tests

on:
  pull_request:
  push:
    branches:
      - staging

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.1.7

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test
```
