### ISSUE TITLE
turbo-ignore is only checking the against the previous commit when running outside of Vercel

### ISSUE THREAD

**Issue by ChristianIvicevic** [vercel/turbo#1641]
### What version of Turborepo are you using?

1.4.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

First, let me point out that I know that `turbo-ignore` is experimental, but I wanted to use it regardless until I have time to write my own customized implementation.

Second, I am building my apps in the GitHub pipeline and pushing prebuilt artifacts via CLI rather than doing anything on Vercel itself. Thus I noticed a bug after creating multiple commits that `turbo-ignore` reported wrong results as it only compares the two commits.

### Expected Behavior

Even with multiple commits at once `turbo-ignore` should deduce the result correctly by comparing against the origin version of the current branch.

### To Reproduce

Make a commit affecting package A, then a commit affecting package B but not A, then `tubo-ignore` will report only B needs to be rebuilt.

**Comment by ChristianIvicevic** [comment]
Previously I have been using Nx so naturally I have been looking for an alternative to `nx-ignore` and completely forgot about the [`nrwl/nx-set-shas`](https://github.com/nrwl/nx-set-shas) action which is pretty decent as it actually solves the aforementioned issue and enables me to use a custom filter of `--filter=scope...[$NX_HEAD...$NX_BASE]`. I can highly recommend looking into collaborating to generalize said action for similar uses.

**Comment by tknickman** [comment]
Hey @ChristianIvicevic thanks for the report - we definitely want to make this work a bit better, and this use case is good one. I'll take a look at [nrwl/nx-set-shas](https://github.com/nrwl/nx-set-shas), and in the meantime would it be helpful if we allowed the comparison argument to be provided via CLI so you could be a bit smarter about it if you needed?

Something like `npx turbo-ignore --comparison HEAD^10`

Right now you can optionally pass in the _scope_ (the left hand side of a [package filter](https://turborepo.org/docs/core-concepts/filtering#filter-by-changed-packages) via arguments, but the right hand comparator is currently un-configurable)

**Comment by ChristianIvicevic** [comment]
> Something like `npx turbo-ignore --comparison HEAD^10`

That is unfortunately a bit unrealiable. Say you have made a change to an app 15 commits ago and changed only another app in the last 10, hence the former wouldn't be built. Any arbitrary number isn't sufficient which is why a robust solution is necessary which must be somewhat dependent on the environment it runs in.

I have snipped most of the parts of `turbo-ignore` and just run it customized in my CI using the nrwl action as it fits my workflow:
```javascript
// ...
const head = process.argv[3];
const base = process.argv[4];
if (!head || !base) {
  console.log(`\u226B Head and base refs for comparison must be defined.`);
  console.log(`\u226B Proceeding with build...`);
  process.exit(1);
}

// Build, and execute the command
const command = `pnpm turbo run build --filter=${scope}...[${head}...${base}] --dry=json`;
// ...
```
My respective GitHub Action workflow is just the following for the time being
```yaml
- name: Clone Repository
  uses: actions/checkout@v3
  with:
    fetch-depth: 0
- name: Set SHAs
  uses: nrwl/nx-set-shas@v2
# ...
- name: Find Affected Projects
  id: affected_projects
  run: |
    NEEDS_DEPLOY=0
    (node scripts/turbo-affected.js website $NX_HEAD $NX_BASE) || NEEDS_DEPLOY=1
    echo "::set-output name=deploy_website::${NEEDS_DEPLOY}"
# ...
website:
  name: Website
  uses: ./.github/workflows/_deploy_vercel.yaml
  needs: validate
  if: ${{ needs.validate.outputs.deploy_website != 0 }}
```
