### ISSUE TITLE
Remote cache miss despite --dry-run=json reporting "remote": true

### ISSUE THREAD

**Issue by mike-hogan** [vercel/turbo#2246]
### What version of Turborepo are you using?

1.5.6

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Github actions reports a cache miss like this:

```
@docsndata/ops-team-backup:build: cache miss, executing d15aaa2304d06baf
```

Running `npx turbo build --dry-run=json` locally reports this:

```
{
      "taskId": "@docsndata/ops-team-backup#build",
      "task": "build",
      "package": "@docsndata/ops-team-backup",
      "hash": "d15aaa2304d06baf",
      "cacheState": {
        "local": false,
        "remote": true
      },
      "command": "tsc -p tsconfig.json \u0026\u0026 tsc -p tsconfig-cjs.json",
      "outputs": [
        ".svelte-kit/**",
        "dist/**",
        "package/**"
      ],
      "excludedOutputs": null,
      "logFile": "ops/team-backup/.turbo/turbo-build.log",
      "directory": "ops/team-backup",
      "dependencies": [
        "@docsndata/data-graphql#build",
        "@docsndata/ops-monitor#build",
        "@docsndata/data-graphql-for-tables#build",
        "@docsndata/model-team#build",
        "@docsndata/model-types#build",
        "@docsndata/data-backend-tables#build",
        "@docsndata/lang-util#build",
        "@docsndata/lang-lodash#build",
        "@docsndata/data-backend-test-schema#build",
        "@docsndata/model-core2#build",
        "@docsndata/testing-stub-graphql#build"
      ],
      "dependents": [
        "@docsndata/ops-cli#build",
        "@docsndata/ops-team-restore#build"
      ]
    }
```

My github actions yml file is:

```
name: CI


on:
  push:
    branches: ["master"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
#    runs-on: self-hosted
#     To use Remote Caching, uncomment the next lines and follow the steps below.
    env:
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7
          run_install: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Running postinstall script
        run: ./scripts/postinstall.sh

      - name: Build
        run: npx turbo build

      - name: Test
        run: npx turbo test
```

My monorepo consists of 152 packages.  Github actions always gets cache misses, but never the same ones.  It made me wonder if maybe the remote cache server was failing http calls under load.  But that is conjecture.

Running `npx turbo build --remote-only` locally reports a full cache hit.

### Expected Behavior

I expected a cache hit for given hash

### To Reproduce

I don't have a small reproduction of this problem.  It varies each time I run the github action.
