### ISSUE TITLE
[Turbopack] Error resolving css request

### ISSUE THREAD

**Issue by lelabo-m** [vercel/turbo#2377]
### What version of Turbopack are you using?

next 13.0.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Turbopack seems to have difficulty parsing some CSS files (it may be related to #2356).

When adding `@tailwindcss/forms` to tailwind and running my app with `concurrently \"next dev --turbo\" \"npm run tailwind --watch\"`, I get the following errors :

```
[0] error - [resolve]
[0]   styles
[0]     Error resolving URI imports: not implemented yet
[0]     unable to resolve uri "data:" "image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3ccircle cx='8' cy='8' r='3'/%3e%3c/svg%3e"
[0] 
[0]     Error resolving URI imports: not implemented yet
[0]     unable to resolve uri "data:" "image/svg+xml,%3csvg viewBox='0 0 16 16' fill='white' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M12.207 4.793a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0l-2-2a1 1 0 011.414-1.414L6.5 9.086l4.293-4.293a1 1 0 011.414 0z'/%3e%3c/svg%3e"
[0] 
[0]     Error resolving URI imports: not implemented yet
[0]     unable to resolve uri "data:" "image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 16 16'%3e%3cpath stroke='white' stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M4 8h8'/%3e%3c/svg%3e"
```

### Expected Behavior

Turbopack should be able to parse this CSS:
```css
select {
  background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='none' viewBox='0 0 20 20'%3e%3cpath stroke='%236b7280' stroke-linecap='round' stroke-linejoin='round' stroke-width='1.5' d='M6 8l4 4 4-4'/%3e%3c/svg%3e");
[...]
}
```

### To Reproduce

Use the following [nextjs example repo](https://github.com/vercel/next.js/tree/canary/examples/with-turbopack).

Add the following package: `@tailwindcss/forms`
Add the tailwind plugin (`plugins: [require('@tailwindcss/forms')]`) to `tailwind.config.js` such as:

```javascript
module.exports = {
  content: [...],
  theme: {
  [...]
  },
  plugins: [require('@tailwindcss/forms')],
};
```

Then modify your dev script in package.json:
```json
{
  "scripts": {
    "dev": "concurrently \"next dev --turbo\" \"npm run tailwind --watch\""
  }
}
```

And run the example: `npm run dev` or `pnpm dev`

### Reproduction Repo

https://github.com/vercel/next.js/tree/canary/examples/with-turbopack
