### ISSUE TITLE
[turborepo] Yarn Berry Prune leaves `dependenciesMeta` when empty (fails `--immutable`)

### ISSUE THREAD

**Issue by quinnturner** [vercel/turbo#2590]
### What version of Turborepo are you using?

v1.6.3

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Improper Yarn Berry turbo prune result, leaves `dependenciesMeta`

![image](https://user-images.githubusercontent.com/12538019/199965119-52d2a731-e592-46f2-9ccf-2c5ca0100c7a.png)

For this dependency:

```yml
"jest-launchdarkly-mock@npm:^1.0.6":
  version: 1.0.6
  resolution: "jest-launchdarkly-mock@npm:1.0.6"
  dependencies:
    lodash.camelcase: ^4.3.0
    lodash.kebabcase: ^4.1.1
    lodash.snakecase: ^4.1.1
  peerDependencies:
    launchdarkly-react-client-sdk: ^2.25.1
    react: ">=17.0.2"
  dependenciesMeta:
    universal-hot-reload@3.3.9:
      unplugged: true
  checksum: 000b6f865f2e299111e9e82f6f9f345ce7244e7d97d544b0d3fb51d2dc5c004f9fcb1fb734d212c10678932e4533026d343a1962a570a31273d7725fe6bc106c
  languageName: node
  linkType: hard
```

### Expected Behavior

Pass `--immutable`

### To Reproduce

Install `jest-launchdarkly-mock@npm:1.0.6` in a package that is intended to be kept during a prune (in my my case, the `--scope` target) then `turbo prune --scope target`
