### ISSUE TITLE
[turborepo] remote cache not hitting in bitbucket pipeline

### ISSUE THREAD

**Issue by lenhosseini** [vercel/turbo#3005]
### What version of Turborepo are you using?

1.6.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Remote cache never hits in bitbucket pipeline, but says that remote cache is enabled 

![SCR-20221214-l2y](https://user-images.githubusercontent.com/96687967/207618657-2bbe8620-82cc-4e4c-9de0-134559d917dc.png)

### Remote caching does work locally after deleting local cache
```sh
rm -rf ./node_modules/.cache/turbo
```

### Expected Behavior

After running the pipeline once, running it again without changes will lead to turbo repo remote caching hit

## Steps to reporoduce

- [ ] create new turbo repo starter
- [ ] enable remote caching
- [ ] create bitbucket-pipelines.yml file
- [ ] add TURBO_TOKEN and TURBO_TEAM variable to bitbucket Repository variable
- [ ] push code to repository
- [ ] re run pipeline without changes

### bitbucket-pipelines.yml
```yml
image: node:16

pipelines:
  branches:
    master:
      - step:
          name: 'Install, Format & Lint, Build'
          caches:
            - node
          script:
            - yarn install --frozen-lockfile
            - yarn build
```
### turbo.json
```json
{
	"$schema": "https://turbo.build/schema.json",
	"pipeline": {
		"build": {
			"dependsOn": ["^build"],
			"outputs": ["dist/**", ".next/**"]
		},
	}
}

```
