### ISSUE TITLE
[Meta] Can you add .github/release.yml to this repository?

### ISSUE THREAD

**Issue by azu** [vercel/turbo#3261]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

It looks like recent release note is very long.

- [Release v1.7.0 · vercel/turbo](https://github.com/vercel/turbo/releases/tag/v1.7.0)

It looks like good that add `.github/release.yml` and categorize PR.
It will improve readbility of release note.

- [Automatically generated release notes - GitHub Docs](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)

### Describe the solution you'd like

I created an example of `.github/release.yml` for https://github.com/vercel/turbo/labels

```yaml
changelog:
  exclude:
    labels:
      - 'pr: publishing' # This label is not really there, but perhaps a PR to PUBLISH should be excluded.

  categories:
    - title: Turbopack
      labels: 
        - 'area: turbopack'
    - title: Turborepo
      labels: 
        - 'area: turborepo'
    - title: WebSite
      labels: 
        - 'area: site'
    - title: Logging
      labels: 
        - 'area: logging'
    - title: Examples
      labels:
        - 'area: examples'
    - title: CI
      labels: 
        - 'area: ci'
    - title: Caching
      labels: 
        - 'area: caching'
    - title: Documents
      labels:
        - 'area: docs'
    - title: Developer experience
      labels:
        - 'area: ergonomics'
    - title: Other Changes
      labels: 
        - "*"
```

### Describe alternatives you've considered

- Use [changesets](https://github.com/changesets/changesets)
