### ISSUE TITLE
[turborepo] panicked at main when running via docker on latest (1.8.3)

### ISSUE THREAD

**Issue by caomicc** [vercel/turbo#4059]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm having an error where after the recent update I am unable to start up my turborepo in docker as it says it has panicked

```
magma            | 
magma            | To address issues that do not require attention, run:
magma            |   npm audit fix
magma            | 
magma            | To address all issues possible (including breaking changes), run:
magma            |   npm audit fix --force
magma            | 
magma            | Some issues need review, and may require choosing
magma            | a different dependency.
magma            | 
magma            | Run `npm audit` for details.
magma-storybook  | thread 'main' panicked at 'Failed to execute turbo.: Os { code: 8, kind: Uncategorized, message: "Exec format error" }', crates/turborepo-lib/src/shim.rs:398:14
magma-storybook  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
magma            | thread 'main' panicked at 'Failed to execute turbo.: Os { code: 8, kind: Uncategorized, message: "Exec format error" }', crates/turborepo-lib/src/shim.rs:398:14
magma            | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
magma-storybook exited with code 101
magma exited with code 0
```

My dockerfile contains the line `RUN npm -g install turbo` I have also tried `RUN npm -g install turbo@1.8.3` and in those instances it will fail. 

When I set it to a previous version such as 1.6.3 it runs as expected

I am able to pin to the version 1.6.3, but I wanted to report nonetheless

### Expected Behavior

I would expect my nextjs app to run on `turbo run dev` on the latest version as it does on 1.6.3 or instructions on how to upgrade 😅

## docker-compose.yml
```
version: "3"
services:
  # turborepo
  turbo:
    container_name: magma
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    command: sh -c "npm install && turbo run dev"
    volumes:
      - ./:/app/
        # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    restart: always
  storybook:
    container_name: magma-storybook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6006:6006"
    command: sh -c "npm install && turbo run storybook"
    volumes:
      - ./:/app/
        # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    restart: always
networks:
  turbo-network:
    driver: bridge
```

## Dockerfile
```
FROM node:16-alpine

ENV NODE_ENV development

# https://github.com/vercel/turbo/issues/2198
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache \ 
    make \
    libc6-compat \
    python3 \
    g++ \
    jpeg-dev \
    cairo-dev \
    giflib-dev \
    pango-dev
RUN apk update

# add turborepo
RUN npm -g config set user root
RUN npm -g install turbo@1.6.3

# Set working directory
WORKDIR /app

# Install app dependencies
COPY  ["package-lock.json", "package.json", "./"] 

# Copy source files
COPY . .

# Install app dependencies
RUN npm install

EXPOSE 3000 3001 3002 6006
```

## turbo.json
```
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**", "storybook-static/**"],
      "env": [
        ***
      ]
    },
    "test": {
      "dependsOn": ["^build"],
      "outputs": []
    },
    "cypress:open": {
      "dependsOn": ["^dev"],
      "outputs": []
    },
    "cypress:run": {
      "dependsOn": ["^dev"],
      "outputs": []
    },
    "lint": {
      "outputs": []
    },
    "lint-fix": {
      "outputs": []
    },
    "dev": {
      "cache": false
    },
    "start": {
      "cache": false
    },
    "storybook": {
      "cache": false
    }
  },
  "globalEnv": [
    ***
  ],
  "globalDependencies": [".env"]
}
```
