### ISSUE TITLE
[turborepo] Github actions cache miss 

### ISSUE THREAD

**Issue by walterholohan** [vercel/turbo#4171]
### What version of Turborepo are you using?

1.8.3

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

Hi,

We are using remote cache with Github actions to deploy our serverless services. Everything works great locally and remotely except for one of our services which will always get a cache miss when deploying on Github actions. Locally I have tried setting `--remote-only` flag and removing local cache which still results in cache hits. Which means that the cache is available remotely. We are currently on the Hobby vercel plan. Will this affect anything, as the service that's causing issues is our largest service. Is their API limits when downloading remote cache to Github actions machine?

### Expected Behavior

We should get a cache HIT, both cache keys are the same values i.e. 

local: `cache hit, replaying output 1951dee53252af40`
github actions: `cache miss, replaying output 1951dee53252af40`

### To Reproduce

Add remote caching to your Github actions deployment e.g. GHA code below

```
name: Deploy main branch to staging

on:
  push:
    branches:
      - main

concurrency:
  group: ci-staging
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-20.04
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Turbo lint
        run: npm run lint

      - name: Turbo tests
        run: npm run test:ci

      - name: Turbo serverless deploy
        run: npm run deploy:ci -- -s staging
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
```
