### ISSUE TITLE
Cache hits don't occur in Github Actions workflows

### ISSUE THREAD

**Issue by sammccord** [vercel/turbo#451]
### What version of Turborepo are you using?

1.0.23

### What package manager are you using / does the bug impact?

npm / pnpm

### What operating system are you using?

Linux

### Describe the Bug

When attempting to achieve full turbo speeds in GHA workflows by caching `turbo`'s cache with `actions/cache@v2`, the restored cache isn't respected in subsequent workflow runs, and results in misses even when there aren't any changes to source files.

This occurs regardless of the `--cache-dir` arg, or if packages' `.turbo/*.log`s are included in the cache.

<3 this project btw

### Expected Behavior

Turbo should use the cache folder restored by `actions/cache@v2`

### To Reproduce

Here's a basic reproduction using the default template - https://github.com/sammccord/ga-repro

If you check out [this run](https://github.com/sammccord/ga-repro/runs/4648241357?check_suite_focus=true), when I build with a cache that should be valid, it instead misses all packages and creates new entries in the cache.

![image](https://user-images.githubusercontent.com/1815885/147542954-dbc48744-1155-41a4-8604-c6d6a75a2736.png)

I can't reproduce on my Linux box or Mac lappy, everything works peachy there.

**Comment by xiaoyu-tamu** [comment]
```yml
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          node-version: '16'

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn
      - name: Build
        run: |
          yarn run build --cache-dir=".turbo"
```

![image](https://user-images.githubusercontent.com/33362998/147631611-694142db-0daf-4b36-99ff-13c7507c3b52.png)

**Comment by sammccord** [comment]
@xiaoyu-tamu What you're suggesting is a workaround, but it's still a bug that turbo's caching does not work consistently between package managers the docs claim to support.

**Comment by kieranm** [comment]
@xiaoyu-tamu This workaround worked for me, but only if I specified...
```
with:
  path: node_modules/.cache/turbo
```
instead of:
```
with:
  path: .turbo
```

**Comment by nicksrandall** [comment]
Also seeing this.

**Comment by luismramirezr** [comment]
I had it solved by defining the `cache-dir` outside the `node_modules` directory. If I let the cache dir inside the `node_modules`, the hash changes between every turbo run.
```yaml
   - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-
```

and then when running the turbo commands: `yarn turbo run <pipeline> --cache-dir=.turbo`
