### ISSUE TITLE
[turborepo] HEAD^ filter on shallow clone stopped working in 1.9.1

### ISSUE THREAD

**Issue by laat** [vercel/turbo#4559]
### What version of Turborepo are you using?

1.9.2

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

Turbo tries to read a commit before HEAD^ when filtering.

`npx turbo@1.9.2 run build --filter "...[HEAD^]" --dry json` fails with the message:

```
Turbo error: failed to resolve packages to run: git error: object not found - no match for id (d9f5424696e8aa64fa7c92b88ee8d96bd529f008); class=Odb (9)
```

### Expected Behavior

It should probably work on a shallow clone

### To Reproduce

A repro, with a PR that fails with 1.9.1:

https://github.com/laat/turbo-shallow-repro/pull/2

The Github Action:
```yaml
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-node@v3

    # works
    - run: npx turbo@1.9.0 run build --filter "...[HEAD^]" --dry json
    
    # fails
    - run: npx turbo@1.9.1 run build --filter "...[HEAD^]" --dry json
   
    # fails
    - run: npx turbo@1.9.2 run build --filter "...[HEAD^]" --dry json
      if: always()
```
