### ISSUE TITLE
[turbopack] 

### ISSUE THREAD

**Issue by OttlikG** [vercel/turbo#5602]
### What version of Next.js are you using Turbopack in?

13.4.12

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Describe the Bug

When I had the following class declaration:
```jsx
<div className={`sameLevel ${styles.simpleClass}`}>
    { children }
</div>
```
and had the following scss:
```scss
:global(.sameLevel) {
    &.simpleClass {
        display: flex;
        ...
    }
}
```
Turbopack wasn't including my classname.

### Expected Behavior

It should compile to:
```jsx
<div className={`manage simpleClass`}>
    { children }
</div>
```

When I used the following syntax, it worked:
```jsx
<div className={`upperLevel`}>
    <div className={`${styles.simpleClass}`}>
        { children }
    </div>
</div>
```

```scss
:global(.upperLevel) {
    .simpleClass {
        display: flex;
        ...
    }
}
```

### To Reproduce

It's reproducible with the provided code.

**Comment by kdy1** [comment]
# Investigation


## Input

Output:
```css
.sameLevel {
  &.__local__simpleClass {
    display: flex;
  }
}

```

## Workaround

Output:
```css
.upperLevel {
  .__local__simpleClass {
    display: flex;
  }
}


```


So `&` is not dropped
