### ISSUE TITLE
[turborepo] Turbo error: unable to find any locator for string_decoder@0.1

### ISSUE THREAD

**Issue by robinelvin** [vercel/turbo#6232]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

Running `yarn turbo prune` on one of my projects in a monorepo results in some (all?) files being produced in `out` but the command fails with: `Turbo error: unable to find any locator for string_decoder@0.1`

Running `yarn why string_decoder@0.1` comes back with nothing and `yarn why string_decoder` shows a lot of different versions none of which are 0.1

```
yarn why string_decoder
├─ raw-body@npm:1.1.7
│  └─ string_decoder@npm:0.10.31 (via npm:0.10)
│
├─ readable-stream@npm:2.3.7
│  └─ string_decoder@npm:1.1.1 (via npm:~1.1.1)
│
├─ readable-stream@npm:2.3.8
│  └─ string_decoder@npm:1.1.1 (via npm:~1.1.1)
│
├─ readable-stream@npm:3.6.2
│  └─ string_decoder@npm:1.3.0 (via npm:^1.1.1)
│
└─ readable-stream@npm:4.4.2
   └─ string_decoder@npm:1.3.0 (via npm:^1.3.0)
```

I have removed `node_modules` and `yarn.lock` and reinstalled and still get the same issue. Yarn itself never complains and my builds all work.

### Expected Behavior

The command should work

### To Reproduce

I'm unable to find how to reproduce this as filtering by another scope in my monorepo works fine. This seems to be related to a particular scope.

**Comment by chris-olszewski** [comment]
Could you provide your lockfile? (Either here or privately share a copy with me via a private repository)

**Comment by robinelvin** [comment]
Here you go:

```
"raw-body@npm:~1.1.0":
  version: 1.1.7
  resolution: "raw-body@npm:1.1.7"
  dependencies:
    bytes: 1
    string_decoder: 0.10
  checksum: 75ab1815ac54992abccccdffb27bd9ad9f5b6f5fb66e740474ad0d1bd3c1425e407b2be5eb34e0bef3da2c66bfa6a2c2b77498596f5b9999ead2d449fff0226f
  languageName: node
  linkType: hard
  ```
  
```
"string_decoder@npm:0.10":
  version: 0.10.31
  resolution: "string_decoder@npm:0.10.31"
  checksum: fe00f8e303647e5db919948ccb5ce0da7dea209ab54702894dd0c664edd98e5d4df4b80d6fabf7b9e92b237359d21136c95bf068b2f7760b772ca974ba970202
  languageName: node
  linkType: hard
```

Full file: [yarn.lock](https://gist.github.com/robinelvin/827f599c9347fcfc5fff51cf78743d68)

I wonder if it's something as simple as Turbo parsing the `0.10` as `0.1`....
