### ISSUE TITLE
[turborepo] Yarn v4 patch causes `turbo prune` to panic, no locator found

### ISSUE THREAD

**Issue by quinnturner** [vercel/turbo#6450]
### What version of Turborepo are you using?

1.10.16

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

```txt
yarn turbo prune --scope MobileApp
Generating pruned monorepo for MobileApp in /Users/username/projectname
 - Added @project/client-shared
 - Added @project/core
 - Added @project/graphql
 - Added @project/openapi
 - Added @project/tsconfig
 - Added @project/types
 - Added MobileApp
 - Added eslint-config-project
thread 'main' panicked at crates/turborepo-lockfiles/src/berry/mod.rs:456:44:
No locator found for @openapi-codegen/typescript@npm:^6.2.0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Where I have the following (simplified) `package.json`:

root:

```json
{
  "packageManager": "yarn@4.0.2",
  "resolutions": {
    "@openapi-codegen/typescript@^6.2.0": "patch:@openapi-codegen/typescript@npm%3A6.2.0#./.yarn/patches/@openapi-codegen-typescript-npm-6.2.0-c197461d23.patch"
  }
}
```

`@project/openapi`

```json
{
  "name": "@project/openapi",
  "devDependencies": {
    "@openapi-codegen/typescript": "^6.2.0"
  }
}
```

Partial `yarn.lock`

```yml
"@openapi-codegen/typescript@npm:6.2.0":
  version: 6.2.0
  resolution: "@openapi-codegen/typescript@npm:6.2.0"
  dependencies:
    case: "npm:^1.6.3"
    lodash: "npm:^4.17.21"
    openapi3-ts: "npm:^2.0.1"
    pluralize: "npm:^8.0.0"
    tslib: "npm:^2.3.1"
    tsutils: "npm:^3.21.0"
    typescript: "npm:4.8.2"
  checksum: cbf9d6cbd1489cd47e79cb28aed5a2e3f882aca58d30f3a5a83ad5ca943af656df7c4e780abf49de78fb316ebcbd7cb79fd9b64b7d7183d14d76a6985331d4df
  languageName: node
  linkType: hard

"@openapi-codegen/typescript@patch:@openapi-codegen/typescript@npm%3A6.2.0#./.yarn/patches/@openapi-codegen-typescript-npm-6.2.0-c197461d23.patch::locator=project%40workspace%3A.":
  version: 6.2.0
  resolution: "@openapi-codegen/typescript@patch:@openapi-codegen/typescript@npm%3A6.2.0#./.yarn/patches/@openapi-codegen-typescript-npm-6.2.0-c197461d23.patch::version=6.2.0&hash=ed8498&locator=project%40workspace%3A."
  dependencies:
    case: "npm:^1.6.3"
    lodash: "npm:^4.17.21"
    openapi3-ts: "npm:^2.0.1"
    pluralize: "npm:^8.0.0"
    tslib: "npm:^2.3.1"
    tsutils: "npm:^3.21.0"
    typescript: "npm:4.8.2"
  checksum: ec10908cbf51fb704066ba591f1294f389ab4606063ad76359061d3db35ad6d045bc88e8b09c0469dffe9a61f53d111533525054b1ec8f85febc17f005befb61
  languageName: node
  linkType: hard
  
"@project/openapi@workspace:*, @project/openapi@workspace:packages/openapi":
  version: 0.0.0-use.local
  resolution: "@project/openapi@workspace:packages/openapi"
  dependencies:
    "@openapi-codegen/typescript": "npm:^6.2.0"
    "@project/tsconfig": "workspace:*"
  languageName: unknown
  linkType: soft

```

### Expected Behavior

Should not panic.

### To Reproduce

1. (I started with a Yarn 3 patch then upgraded to Yarn 4. You might be able to create a patch on Yarn 4 immediately rather than 3 -> 4, not sure).
2. Have a patch exist for a dependency in one of the packages in the prune
3. Run `yarn prune`

I can email you a link to a repo if needed.

<sub>[TURBO-1719](https://linear.app/vercel/issue/TURBO-1719/[turborepo]-yarn-v4-patch-causes-turbo-prune-to-panic-no-locator-found)</sub>
