### ISSUE TITLE
Turborepo prune omits monorepo dependencies

### ISSUE THREAD

**Issue by robinelvin** [vercel/turbo#7732]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

N/A

### What package manager are you using / does the bug impact?

Yarn v2/v3/v4 (node_modules linker only)

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

1.12.5-canary.2

### Describe the Bug

Prior to upgrading to the latest Turbo the prune command would copy monorepo dependencies. Now it only copies the specified package e.g.

With v1.10.16

```
╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│                  Update available v1.10.16 ≫ v1.12.5                  │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.12.5    │
│               Run "npx @turbo/codemod update" to update               │
│                                                                       │
│        Follow @turborepo for updates: https://x.com/turborepo         │
╰───────────────────────────────────────────────────────────────────────╯
Generating pruned monorepo for @elixirsoftware/core-api in /Volumes/Crucial X8/Projects/Elixir/core-develop/api_out
 - Added @elixirsoftware/core-api
 - Added @elixirsoftware/core-common
 - Added @elixirsoftware/dal
```

With v1.12.5

```

Attention:
Turborepo now collects completely anonymous telemetry regarding usage.
This information is used to shape the Turborepo roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://turbo.build/repo/docs/telemetry

Generating pruned monorepo for @elixirsoftware/core-api in /Volumes/Crucial X8/Projects/Elixir/core-develop/api_out
 - Added @elixirsoftware/core-api
```

This means that the pruned output cannot be built due to missing peer dependencies

### Expected Behavior

It should copy dependencies to allow the build.

### To Reproduce

Create a monorepo with a package depending on another in the same monorepo. Set up Turbo build dependencies such that when the main package is built it builds the dependency first. Use `turbo prune --docker --out-dir=./out <main-package>`

### Additional context

Tested with latest v1.12.5 and latest canary release which both exhibit the undesired behaviour.
*Confirmed working correctly in v.1.12.4

**Comment by chris-olszewski** [comment]
Please include a reproduction repo of the issue. I'm unable to reproduce the behavior given your description.

**Comment by chris-olszewski** [comment]
@robinelvin If you are unable to provide a complete reproduction repo could you provide the following:
 - What version of Yarn you're using
 - Contents of `.yarnrc.yml`
 - How dependencies from `@elixirsoftware/core-api` are declared to `@elixirsoftware/core-common` and `@elixirsoftware/dal`
 - Versions of all of the packages mentioned

**Comment by robinelvin** [comment]
Hi @chris-olszewski 

Sorry, I've been really busy and not been able to produce a reproduction. To answer your questions:

I'm using Yarn 4.0.2 in PnP mode

.yarnrc.yml

```yaml
compressionLevel: mixed

enableGlobalCache: false

enableInlineBuilds: true

nodeLinker: pnp

packageExtensions:
  "@aws-sdk/token-providers@*":
    dependencies:
      "@aws-sdk/region-config-resolver": "*"
  "@cucumber/cucumber@*":
    dependencies:
      tsx: "*"
  local-pkg@*:
    peerDependencies:
      happy-dom: "*"
  typeorm@*:
    peerDependencies:
      mysql: "*"
  vite@*:
    dependencies:
      jsdom: "*"
      supports-color: "*"
  vitest@*:
    dependencies:
      jsdom: "*"
    peerDependencies:
      supports-color: "*"

plugins:
  - checksum: 0141f8cfb8a5ea41428cc0a49cf412f0cf13a3f3f9e51ef354768b5c988c93d0adc46c318d11b6da858b9ce9a9c8db0069712c10be35f9ac440071bc00bc4216
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"
  - path: .yarn/plugins/@ojkelly/plugin-all.cjs
    spec: "https://yarn.build/latest"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
```
The package dependencies are sibling workspaces declared in `package.json` as "devDependencies" like this:

```json
        "@elixirsoftware/core-common": "workspace:packages/core-common",
        "@elixirsoftware/dal": "workspace:packages/dal",
```
